services:
  - type: web
    name: bmi-calculator
    env: python
    buildCommand: |
      mkdir -p model
      cp custom_cnn_bmi_model_final.keras model/
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
