services:
  - type: web
    name: bmi-calculator
    env: python
    buildCommand: |
      # Create necessary directories
      mkdir -p model uploads

      # Install required packages
      pip install -r requirements.txt
      pip install gdown

      # Download the model file from Google Drive
      echo "Downloading model file from Google Drive..."
      FILE_ID="18Qv7ipbhfAer0XxfnBxPc2vUNedEbJhj"
      gdown --id $FILE_ID -O model/custom_cnn_bmi_model_final.keras || {
        echo "Failed to download model file"
        exit 1
      }

      # Verify model file exists
      if [ ! -f "model/custom_cnn_bmi_model_final.keras" ]; then
        echo "Model file not found after download"
        exit 1
      fi

      # Copy model to root directory for compatibility
      cp model/custom_cnn_bmi_model_final.keras custom_cnn_bmi_model_final.keras
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
