services:
  - type: web
    name: bmi-calculator
    env: python
    buildCommand: |
      # Create necessary directories
      mkdir -p model uploads

      # Install required packages
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gdown

      # Download the model file from Google Drive
      echo "Downloading model file from Google Drive..."
      FILE_ID="18Qv7ipbhfAer0XxfnBxPc2vUNedEbJhj"
      gdown --id $FILE_ID -O model/custom_cnn_bmi_model_final.keras || {
        echo "Failed to download model file"
        exit 1
      }

      # Verify model file exists and has content
      if [ ! -f "model/custom_cnn_bmi_model_final.keras" ]; then
        echo "Model file not found after download"
        exit 1
      fi

      MODEL_SIZE=$(stat -c%s "model/custom_cnn_bmi_model_final.keras")
      if [ "$MODEL_SIZE" -lt 1000000 ]; then
        echo "Model file appears to be too small ($MODEL_SIZE bytes)"
        exit 1
      fi

      # Copy model to root directory for compatibility
      cp model/custom_cnn_bmi_model_final.keras custom_cnn_bmi_model_final.keras

      # Verify the copy was successful
      if [ ! -f "custom_cnn_bmi_model_final.keras" ]; then
        echo "Failed to copy model file to root directory"
        exit 1
      fi
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
